version: '3.8'

services:

    mariadb:
        image: mariadb
        container_name: app_db
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "9826:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: app_phpmyadmin
        restart: always
        environment:
            - PMA_HOST=app_db
            - UPLOAD_LIMIT=5242880000
        ports:
            - "9825:80"

    redis:
        image: "redis:latest"
        container_name: app_redis
        restart: always
        ports:
            - "6379:6379"


    php:
        image: php:8.2-cli
        container_name: app_php
        volumes:
            - ./:/var/www/html
        restart: always
        depends_on:
            - mariadb
            - redis

volumes:
    mariadb_data:
    postgres_data:
